version: '3.4'

services:
  eshopwebmvc:
    image: dannydee93/eshopwebmvc:latest
    depends_on:
      - "sqlserver"
  eshoppublicapi:
    image: dannydee93/eshoppublicapi:latest
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@someThingComplicated1234"
      ACCEPT_EULA: "Y"
