---
apiVersion: v1
kind: Service
metadata:
  name: eshopwebmvc-service
spec:
  selector:
    app: eshopwebmvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi-service
spec:
  selector:
    app: eshoppublicapi
  ports:
    - protocol: TCP
      port: 443
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
